# RESOLUÇÃO EXERCICIO 2:

# lista = ['1', '1']
# for contador in range(2,100):
#     lista.append(int(lista[len(lista) - 2]) + int(lista[len(lista) - 1]))

# chute = int(input("Qual termo quer encontrar: "))

# if chute in lista :
#     print("Você tem razão {} faz parte da sequencia de fibonatti".format(chute))
# else:
#     print("Não {} não faz parte da sequencia de fibonatti".format(chute))
# print ("FIM!")

# RESOLUÇÃO DO EXERCICIO 3:

# RESOLUÇÃO EXERCICIO 4:

# faturamento_sp = 67836.43
# faturamento_rj = 36678.66
# faturamento_mg = 29229.88
# faturanento_es = 27165.48
# faturamento_outros = 19849.53

# faturamento_total = faturamento_sp + faturamento_rj + faturamento_mg + faturanento_es + faturamento_outros
# percentual_faturamento_sp = round((faturamento_sp/faturamento_total)*100)
# percentual_faturamento_rj = round((faturamento_rj/faturamento_total)*100)
# percentual_faturamento_mg = round((faturamento_mg/faturamento_total)*100)
# percentual_faturamento_es = round((faturanento_es/faturamento_total)*100)
# percentual_faturamento_outros = round((faturamento_outros/faturamento_total)*100)

# print(f'''O faturamento mensal total é R${faturamento_total},
#         O percentual do faturamento de São Paulo é {percentual_faturamento_sp}%, 
#         O percentual do faturamento do Rio de Janeiro é {percentual_faturamento_rj}%,
#         O percentual do faturamento de Minas Gerais é {percentual_faturamento_mg}%,
#         O percentual do faturamento do Espirito Santo é {percentual_faturamento_es}%,
#         O percentual do faturamento dos Outros estados é {percentual_faturamento_outros}%''')

# RESOLUÇÃO EXERCICIO 5:

# txt  = "texto invertido" [::-1]
# print (txt)



